// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Position;
lv_obj_t * ui_Calibrate;
lv_obj_t * ui_LabelCalibrate;
lv_obj_t * ui_Koord;
lv_obj_t * ui_KoorCircle;
lv_obj_t * ui_Dot;
lv_obj_t * ui_XYButton;
lv_obj_t * ui_LabelXYButton;
lv_obj_t * ui_YZButton;
lv_obj_t * ui_LabelYZButton;
lv_obj_t * ui_XZButton;
lv_obj_t * ui_LabelXZButton;
lv_obj_t * ui_Container2;
lv_obj_t * ui_Xstr;
lv_obj_t * ui_Ystr;
lv_obj_t * ui_Zstr;
// CUSTOM VARIABLES
lv_obj_t * uic_Screen1;
lv_obj_t * uic_Calibrate;
lv_obj_t * uic_XYButton;
lv_obj_t * uic_Calibrate;
lv_obj_t * uic_XZButton;

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
