// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Position;
extern lv_obj_t * ui_Calibrate;
extern lv_obj_t * ui_LabelCalibrate;
extern lv_obj_t * ui_Koord;
extern lv_obj_t * ui_KoorBase;
extern lv_obj_t * ui_KoorCircle;
extern lv_obj_t * ui_Dot;
extern lv_obj_t * ui_XYButton;
extern lv_obj_t * ui_LabelXYButton;
extern lv_obj_t * ui_YZButton;
extern lv_obj_t * ui_LabelYZButton;
extern lv_obj_t * ui_XZButton;
extern lv_obj_t * ui_LabelXZButton;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Xstr;
extern lv_obj_t * ui_Ystr;
extern lv_obj_t * ui_Zstr;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Screen1;
extern lv_obj_t * uic_Calibrate;
extern lv_obj_t * uic_XYButton;
extern lv_obj_t * uic_Calibrate;
extern lv_obj_t * uic_XZButton;

// EVENTS
extern void ui_event_Calibrate(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
