// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
void calibrate_button(lv_event_t * e)
{
	//calibrate();
	// Your code here
}
