// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x7B610B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Position = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Position);
    lv_obj_set_width(ui_Position, lv_pct(98));
    lv_obj_set_height(ui_Position, lv_pct(98));
    lv_obj_set_align(ui_Position, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Position, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Position, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Position, lv_color_hex(0xB1AF02), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Position, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Position, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Position, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Position, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Position, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Calibrate = lv_btn_create(ui_Position);
    lv_obj_set_width(ui_Calibrate, 100);
    lv_obj_set_height(ui_Calibrate, 50);
    lv_obj_set_x(ui_Calibrate, 25);
    lv_obj_set_y(ui_Calibrate, -25);
    lv_obj_set_align(ui_Calibrate, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_Calibrate, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Calibrate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Calibrate, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Calibrate, lv_color_hex(0x7B6108), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Calibrate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Calibrate, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Calibrate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Calibrate, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Calibrate, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelCalibrate = lv_label_create(ui_Calibrate);
    lv_obj_set_width(ui_LabelCalibrate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCalibrate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelCalibrate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelCalibrate, "Kalibrieren");
    lv_obj_set_style_text_color(ui_LabelCalibrate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelCalibrate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Koord = lv_obj_create(ui_Position);
    lv_obj_set_width(ui_Koord, lv_pct(75));
    lv_obj_set_height(ui_Koord, lv_pct(80));
    lv_obj_set_x(ui_Koord, -25);
    lv_obj_set_y(ui_Koord, -30);
    lv_obj_set_align(ui_Koord, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Koord, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Koord, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Koord, lv_color_hex(0x9A9500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Koord, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KoorCircle = lv_obj_create(ui_Koord);
    lv_obj_set_width(ui_KoorCircle, 300);
    lv_obj_set_height(ui_KoorCircle, 300);
    lv_obj_set_align(ui_KoorCircle, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_KoorCircle, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_KoorCircle, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_KoorCircle, lv_color_hex(0xFDFAA8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_KoorCircle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dot = lv_btn_create(ui_KoorCircle);
    lv_obj_set_width(ui_Dot, 20);
    lv_obj_set_height(ui_Dot, 20);
    lv_obj_set_x(ui_Dot, lv_pct(1));
    lv_obj_set_y(ui_Dot, lv_pct(1));
    lv_obj_set_align(ui_Dot, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Dot, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_Dot, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Dot, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Dot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_XYButton = lv_btn_create(ui_Position);
    lv_obj_set_width(ui_XYButton, 100);
    lv_obj_set_height(ui_XYButton, 50);
    lv_obj_set_x(ui_XYButton, 25);
    lv_obj_set_y(ui_XYButton, 25);
    lv_obj_add_flag(ui_XYButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_XYButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_XYButton, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_XYButton, lv_color_hex(0x7B6108), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_XYButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_XYButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_XYButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_XYButton, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_XYButton, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelXYButton = lv_label_create(ui_XYButton);
    lv_obj_set_width(ui_LabelXYButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelXYButton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelXYButton, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelXYButton, "XY-Achse");
    lv_obj_set_style_text_color(ui_LabelXYButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelXYButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_YZButton = lv_btn_create(ui_Position);
    lv_obj_set_width(ui_YZButton, 100);
    lv_obj_set_height(ui_YZButton, 50);
    lv_obj_set_x(ui_YZButton, 25);
    lv_obj_set_y(ui_YZButton, 80);
    lv_obj_add_flag(ui_YZButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_YZButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_YZButton, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_YZButton, lv_color_hex(0x7B6108), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_YZButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_YZButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_YZButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_YZButton, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_YZButton, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelYZButton = lv_label_create(ui_YZButton);
    lv_obj_set_width(ui_LabelYZButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelYZButton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelYZButton, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelYZButton, "YZ-Achse");
    lv_obj_set_style_text_color(ui_LabelYZButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelYZButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_XZButton = lv_btn_create(ui_Position);
    lv_obj_set_width(ui_XZButton, 100);
    lv_obj_set_height(ui_XZButton, 50);
    lv_obj_set_x(ui_XZButton, 25);
    lv_obj_set_y(ui_XZButton, 135);
    lv_obj_add_flag(ui_XZButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_XZButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_XZButton, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_XZButton, lv_color_hex(0x7B6108), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_XZButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_XZButton, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_XZButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_XZButton, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_XZButton, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelXZButton = lv_label_create(ui_XZButton);
    lv_obj_set_width(ui_LabelXZButton, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelXZButton, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelXZButton, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelXZButton, "X-Z Achse");
    lv_obj_set_style_text_color(ui_LabelXZButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelXZButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Position);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, lv_pct(60));
    lv_obj_set_height(ui_Container2, lv_pct(15));
    lv_obj_set_x(ui_Container2, lv_pct(10));
    lv_obj_set_y(ui_Container2, lv_pct(-1));
    lv_obj_set_align(ui_Container2, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Xstr = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Xstr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Xstr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Xstr, -120);
    lv_obj_set_y(ui_Xstr, 0);
    lv_obj_set_align(ui_Xstr, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Xstr, "X: ");

    ui_Ystr = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Ystr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Ystr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Ystr, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Ystr, "Y: ");

    ui_Zstr = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Zstr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Zstr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Zstr, 120);
    lv_obj_set_y(ui_Zstr, 0);
    lv_obj_set_align(ui_Zstr, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Zstr, "Z: ");

    uic_Screen1 = ui_Screen1;
    uic_Calibrate = ui_Calibrate;
    uic_XYButton = ui_XYButton;
    uic_Calibrate = ui_YZButton;
    uic_XZButton = ui_XZButton;

}
