name=gscope
version=0.3
author=Meik Mittwoch    
category=Sensors
url=https://none.io
architectures=*
includes=gscope.h
sentence=none
paragraph=For Seifert Baumaschinen
name=gscope
maintainer= Meik Mittwoch
maintainer_email=meik.sitter@gmx.de


